### PR TITLE
Concatenate ino files before building

### PR DESCRIPTION
**Pull request by mmaret**
As describe in the Adruino Build process
(https://www.arduino.cc/en/Hacking/BuildProcess)
ino files are concateneted before building.
So variable defined in a .ino are available in other one

### CODE REVIEW

**Comment by thunderace** [comment]
Hello, the Arduino build process is a little more complicated : cpp and ino files are concateneted (cpp first and ino file last) and you have to add the current directory to the INCLUDE .
I think that only one ino file is supported (to be confirmed).

**Comment by mmaret** [comment]
The page linked in previous comment (https://www.arduino.cc/en/Hacking/BuildProcess) said in section Multi-file sketches:
"When your sketch is compiled, all tabs with no extension are concatenated together to form the "main sketch file". Tabs with .c or .cpp extensions are compiled separately"

**Comment by mmaret** [comment]
The ino files are the one without extension

**Comment by thunderace** [comment]
You're right sorry. but you need to add sketch's directory to the include path(for sketch' include files).

**Comment by mmaret** [comment]
You are right ! I was planning another PR for that. I will do it here.

2016-06-21 14:58 GMT+02:00 thunder notifications@github.com:

**Comment by mmaret-geny** [comment]
Btw, you did a great job with this project !

**Comment by thunderace** [comment]
Your PRs were manualy integrated (because i have made lots of change one hour ago).

I have to add some test sketch now.

Thank you.

**Comment by mmaret-geny** [comment]
Cool, I was looking for spiffs size too !

**Comment by thunderace** [comment]
Another problem : we have to concatenate ino files in the right order : the main ino file at the end no?

**Comment by mmaret** [comment]
I specially try to put the main one at the top.
That's why it's "cat $(TARGET).ino $(filter-out $(TARGET).ino,$^) > $@"
It looks like it's working like that on arduino.

2016-06-22 10:45 GMT+02:00 thunder notifications@github.com:

**Comment by thunderace** [comment]
Yes, but it's not enough as we don't have the tool to create function definitions... so i think that concatenate is not enough.

**Comment by mmaret** [comment]
You are right. In my sketches I make sure that all my function have
déclaration in the main sketch.
But that's not require (anymore ?).
I wonder if the tool to create function declaration from arduino could be
reuse ...

2016-06-22 11:40 GMT+02:00 thunder notifications@github.com:

**Comment by mmaret** [comment]
We may have something here :
https://github.com/michaelbaisch/uDino-Preprocessor
but I cannot make it work on my computer

2016-06-22 12:03 GMT+02:00 Mathieu Maret mathieu.maret@gmail.com:

**Pull request closed without merging**
