### PR TITLE
Mac OS compatibility fixes

### PR DESCRIPTION
**Pull request by ahihi**
Hi,

This patch allows the makefile to work on Mac OS. (10.10 tested)

I believe the changes retain compatibility with Linux & Windows, but can't test those myself.

### CODE REVIEW

**Comment by thunderace** [comment]
Thx for your help.
For now, I can't test your modifications on Windows so i can't merge.

**Comment by ahihi** [comment]
I understand. I'll try to find some time to set up a Cygwin system and try it. :)

**Comment by thunderace** [comment]
Manual merge of you PR (except for the SIZE_REGEX modification).

Tested on CYGWIN and LINUX.

Thx for your help

**Comment by ahihi** [comment]
Ah, did the new SIZE_REGEX cause issues? I changed it because Mac OS grep fails with "empty (sub)expression" on `(foo|)`. It's a weird quirk, different from even FreeBSD…

**Comment by thunderace** [comment]
No issue but the SIZE_REGEX come directly from the platform.txt of the ESP8266 Arduino SDK (with the ending |).
I will test your modification on others platforms.

**Comment by thunderace** [comment]
It's OK : the trailing | is removed for ESP8266 and ESP32

**Pull request closed without merging**
